const cowboyAsset = (file: string) => `/cowboy-renderings/${file}`;
export const cowboyHatRenders: Record<string, Record<string, string>> = {
  Fitted: { "Bone Cattleman": cowboyAsset("1db8kg.png"), "Dark Brown Cattleman": cowboyAsset("1dcn5c.png"), "Mint Cattleman": cowboyAsset("1d9a1s.png"), "Fuchsia Cattleman": cowboyAsset("1d8wm8.png"), "Soft Pink Cattleman": cowboyAsset("1d8pwg.png"), "Red Cattleman": cowboyAsset("1d93c0.png"), "Turquoise Cattleman": cowboyAsset("2f170001-07a6-49bf-82b8-967d685b475a.png"), "Purple Cattleman": cowboyAsset("2cc85e74-dbe2-48ec-aab0-932b42873158.png"), "White Cattleman": cowboyAsset("d37be2d6-2538-4952-a322-5a7ae7354c20.png"), "Sage Green Cattleman": cowboyAsset("f19f6020-3019-4f32-9900-b61dbeeea71e.png") },
  Adjustable: { "White Cowboy Adjustable": cowboyAsset("1dbiuo.png"), "Red Cowboy Adjustable": cowboyAsset("1dbc4w.png"), "Beige Cowboy Adjustable": cowboyAsset("1daypc.png"), "Mocha Cowboy Adjustable": cowboyAsset("1db5f4.png"), "Black Cowboy Adjustable": cowboyAsset("1dbsxc.png"), "Pink Cowboy Adjustable": cowboyAsset("1da7mo.png") },
  "Tear Drop": { "Dark Brown TD Cowboy": cowboyAsset("1dbfa8.png"), "Mocha TD Cowboy": cowboyAsset("1dbm00.png"), "Black TD Cowboy": cowboyAsset("1dcgfk.png") },
  Camo: { "Camo Cowboy": cowboyAsset("1da3og.png") },
  "Poly Blend": { "White Cowboy (Poly)": cowboyAsset("1dc300.png"), "Camel Cowboy (Poly)": cowboyAsset("1d9qmo.png"), "Black Cowboy (Poly)": cowboyAsset("1darzk.png"), "Red Cowboy (Poly)": cowboyAsset("1da7u8.png") },
  Poly: { "White Cowboy (Poly)": cowboyAsset("1dc300.png"), "Camel Cowboy (Poly)": cowboyAsset("1d9qmo.png"), "Black Cowboy (Poly)": cowboyAsset("1darzk.png"), "Red Cowboy (Poly)": cowboyAsset("1da7u8.png") },
  Straw: { "Camel Straw": cowboyAsset("1dahpc.png") }
};
export const baseBandAssets: Record<string, string> = { "Beige Linen": cowboyAsset("3ychtu.png"), Grey: cowboyAsset("3yce36.png"), "Metallic Silver": cowboyAsset("3ychg2.png"), "Dusty Pink": cowboyAsset("3ycksy.png"), "Light Blue": cowboyAsset("3yco5u.png"), Blue: cowboyAsset("3ycriq.png"), Mustard: cowboyAsset("3ycy8i.png"), "Navy Blue": cowboyAsset("3ycuvm.png"), "Dark Brown": cowboyAsset("3yd1le.png"), Champagne: cowboyAsset("3yd4ya.png"), "Metallic Pink": cowboyAsset("3yd8b6.png"), "Bright Pink": cowboyAsset("3ydbo2.png"), "Light Purple": cowboyAsset("3ydf0y.png"), Burgundy: cowboyAsset("3ydidu.png"), "Metallic Green": cowboyAsset("3ydp3m.png"), Black: cowboyAsset("3ydsgi.png"), Brown: cowboyAsset("3yclea.png"), "White Linen": cowboyAsset("3yc7r6.png"), "Sage Green": cowboyAsset("3ycb42.png"), "Brown Chiffon": cowboyAsset("36da8f.png"), "Cream Lace": cowboyAsset("7tffh0.png"), "White Lace": cowboyAsset("7tfm6s.png") };
export const layeredBandAssets: Record<string, string> = { "Gold Chain": cowboyAsset("5rxjhw.png"), "Turq. & Gold Chain": cowboyAsset("92drh0.png"), "Black Bead & Gold": cowboyAsset("92e1jo.png"), "Crystal & Gold Chain": cowboyAsset("5x0jls.png"), "Gold Stars Chain": cowboyAsset("5x0qbk.png"), "Thin Brown Cord": cowboyAsset("5ry9z8.png"), "Rolled Terracotta": cowboyAsset("5rygp0.png"), "Pink Braid": cowboyAsset("92e4wk.png"), "Rolled Pink": cowboyAsset("5ryu4k.png"), "Rolled Teal": cowboyAsset("5rz0uc.png"), "Purple Studs": cowboyAsset("5rz7k4.png"), "Pink Sparkle": cowboyAsset("5rxn2c.png"), "Black Sparkle": cowboyAsset("5rxts4.png"), "White Rope - Studs": cowboyAsset("5juapq.png"), "Off White Rope - Studs": cowboyAsset("5juri6.png"), "Blue Rope - Studs": cowboyAsset("5jv1ku.png"), "Black Rope - Gold Studs": cowboyAsset("5jvida.png"), "Brown Ribbon": cowboyAsset("5jvz5q.png"), "Aqua Rope - Studs": cowboyAsset("5jwcla.png"), "Brown Rope - Studs": cowboyAsset("5juyta.png"), "Red Rope - Studs": cowboyAsset("5jv8i6.png"), "Black Rope - Silver Studs": cowboyAsset("5jvlxq.png"), "Black Chain": cowboyAsset("5jw2q6.png"), "Leaf Chain": cowboyAsset("5jwg5q.png"), "Knotted Rope": cowboyAsset("5jwq8e.png") };
export const featherAssets: Record<string, string> = { Pheasant: cowboyAsset("66ac111a0dab153a92aa512d.png"), "Small Brown Feather": cowboyAsset("66ac111e26478cae640bb813.png"), Peacock: cowboyAsset("66ac11220dab153a92aa51c4.png"), White: cowboyAsset("66ac112626478cae640bbae7.png"), "Pheasant Turq.": cowboyAsset("5rw54k.png"), "Spotted Turq.": cowboyAsset("5rwbuc.png"), Brown: cowboyAsset("5rwik4.png"), Cream: cowboyAsset("5rwp9w.png"), "Brown Turq.": cowboyAsset("5rwvzo.png"), "Light Brown Turq.": cowboyAsset("5rx2pg.png") };
export const charmAssets: Record<string, string> = { "Gold Horseshoe": cowboyAsset("9z5dtj.png"), "Silver Horseshoe": cowboyAsset("9z573r.png"), "Gold Cactus": cowboyAsset("9z4m5j.png"), "Silver Cactus": cowboyAsset("9z4svb.png"), "Gold Cowboy Boot": cowboyAsset("9z4co7.png"), "Gold Heart": cowboyAsset("9z4ppz.png"), Moon: cowboyAsset("9z5kjb.png"), Star: cowboyAsset("9z5xl3.png"), "Gold Snake": cowboyAsset("9z6b0n.png"), "Silver Snake": cowboyAsset("9z6hqf.png") };

