"use client";
import { useMemo, useState } from "react";

const hats = [
  ["The Sunday Stroll", "$138", "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85"],
  ["The Desert Rose", "$148", "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?auto=format&fit=crop&w=900&q=85"],
  ["The After Hours", "$158", "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85"],
] as const;
const accessories = ["Vintage ribbon", "Feather plume", "Turquoise charm", "Brass concho", "Silk scarf"];
const hatChoices = ["Fitted", "Adjustable", "Tear Drop", "Camo", "Poly Blend", "Straw"];
const hatColors = ["Bone", "Dark chocolate", "Beige", "Nude", "Blush", "Sage", "Turquoise", "Black"];
const bands = ["None", "Classic leather", "Vintage ribbon", "Braided jute", "Silk grosgrain"];
const feathers = ["None", "Pheasant", "Small brown", "Peacock", "White", "Cream"];
const charms = ["None", "Gold horseshoe", "Silver cactus", "Cowboy boot", "Gold heart", "Moon", "Star", "Snake"];
const symbols = ["None", "Horseshoe", "Cactus", "Longhorn", "Heart", "Sun", "Arrow", "Butterfly", "Flower", "Star"];
const extrasMenu = ["None", "Match - Black", "Match - Pink", "Match - Red", "Card - Classic", "Card - Western", "Bundle 1", "Feather stem"];
const A = () => <span aria-hidden="true">↗</span>;
function NavDropdown({ label, items }: { label: string; items: Array<[string, string]> }) { return <details className="nav-dropdown"><summary>{label}<span aria-hidden="true">⌄</span></summary><div className="nav-dropdown-menu">{items.map(([text, href]) => <a key={text} href={href}>{text}</a>)}</div></details>; }
function BuilderGroup({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <div className="builder-group"><label>{title}</label>{note && <p className="builder-note">{note}</p>}{children}</div>; }
function OptionGrid({ items, value, onChange, priced }: { items: string[]; value: string; onChange: (v: string) => void; priced?: boolean }) { return <div className="builder-option-grid">{items.map(item => <button className={value === item ? "active" : ""} onClick={() => onChange(item)} key={item}>{item}{priced && item !== "None" && <small>+$8</small>}</button>)}</div>; }
function BuilderSelect({ value, onChange, items }: { value: string; onChange: (v: string) => void; items: string[] }) { return <select className="builder-select" value={value} onChange={e => onChange(e.target.value)}>{items.map(item => <option key={item}>{item}</option>)}</select>; }
function RefSelect({ label, value, onChange, items, price }: { label: string; value: string; onChange: (v: string) => void; items: string[]; price?: string }) { return <section className="ref-section"><div className="ref-section-title"><b>{label}</b><span>{value} {price}</span></div><select value={value} onChange={e => onChange(e.target.value)}>{items.map(item => <option key={item}>{item}</option>)}</select></section>; }
const bandTextureAssets: Record<string, string> = { "band-navy-blue": "https://cdnv2.mycustomizer.com/db091e-64/7ger2p.png", "band-black": "https://cdnv2.mycustomizer.com/db091e-64/7geufl.png", "band-ivory": "https://cdnv2.mycustomizer.com/db091e-64/7gdwup.png", "band-brown-leather": "https://cdnv2.mycustomizer.com/db091e-64/7gg2ap.png", "band-burgundy": "https://cdnv2.mycustomizer.com/db091e-64/7gf15d.png", "band-rolled-terracotta": "https://cdnv2.mycustomizer.com/db091e-64/7gh70h.png", "band-gold-chain": "https://cdnv2.mycustomizer.com/db091e-64/7gha5t.png", "band-vintage-ribbon": "https://cdnv2.mycustomizer.com/db091e-64/7ghk8h.png", "band-braided-jute": "https://cdnv2.mycustomizer.com/db091e-64/7ghqy9.png", "band-pink-braid": "https://cdnv2.mycustomizer.com/db091e-64/7ghdq9.png", "band-blue-braid": "https://cdnv2.mycustomizer.com/db091e-64/7gdtpd.png", "band-silk-scarf": "https://cdnv2.mycustomizer.com/db091e-64/7ghrr5.png", "band-thin-leather": "https://cdnv2.mycustomizer.com/db091e-64/7gh0ap.png" };
const charmGlyphs: Record<string, string> = { "Gold horseshoe": "⌒", "Silver cactus": "♣", "Cowboy boot": "♢", "Gold heart": "♥", Star: "★" };
function DraggableBand({ name, className, src, position, onMove }: { name: string; className: string; src?: string; position: { x: number; y: number }; onMove: (x: number, y: number) => void }) { const [dragging, setDragging] = useState<{ x: number; y: number; originX: number; originY: number } | null>(null); const texture = src || bandTextureAssets[className.split(" ").pop() || ""]; return <div className={`reference-overlay-band ${className}`} role="button" aria-label={`${name} band — drag to position`} style={{ transform: `translate(${position.x}px, ${position.y}px) rotate(-3deg)` }} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setDragging({ x: e.clientX, y: e.clientY, originX: position.x, originY: position.y }); }} onPointerMove={e => { if (dragging) onMove(dragging.originX + e.clientX - dragging.x, dragging.originY + e.clientY - dragging.y); }} onPointerUp={() => setDragging(null)} onPointerCancel={() => setDragging(null)}><img className="reference-band-art" src={texture} alt={`${name} band texture`} draggable="false" /></div>; }
function DraggableCharm({ name, glyph, position, onMove }: { name: string; glyph: string; position: { x: number; y: number }; onMove: (x: number, y: number) => void }) { const [dragging, setDragging] = useState<{ x: number; y: number; originX: number; originY: number } | null>(null); return <div className="reference-overlay-charm" role="button" aria-label={`${name} charm — drag to position`} style={{ transform: `translate(${position.x}px, ${position.y}px)` }} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setDragging({ x: e.clientX, y: e.clientY, originX: position.x, originY: position.y }); }} onPointerMove={e => { if (dragging) onMove(dragging.originX + e.clientX - dragging.x, dragging.originY + e.clientY - dragging.y); }} onPointerUp={() => setDragging(null)} onPointerCancel={() => setDragging(null)}>{glyph}</div>; }
function SimpleCustomizer({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const steps = ["HAT CHOICE / BLEND", "COLOR", "BASE BAND", "LAYERED BAND 1", "LAYERED BAND 2", "BAND TIE PLACEMENT", "FEATHERS", "BRANDING: INITIALS", "ADDITIONAL BRANDING", "BRANDING: SYMBOLS", "BRANDING COMMENTS", "CHARMS + ACCESSORIES", "HAT SIZE", "HAT COMMENTS"];
  const [step, setStep] = useState(0), [blend, setBlend] = useState("Poly"), [color, setColor] = useState("Camel"), [base, setBase] = useState("None"), [layerOne, setLayerOne] = useState("None"), [layerTwo, setLayerTwo] = useState("None"), [tie, setTie] = useState("Tie On The Back"), [feather, setFeather] = useState("None"), [initials, setInitials] = useState(""), [additional, setAdditional] = useState("No"), [additionalText, setAdditionalText] = useState(""), [symbol, setSymbol] = useState("None"), [brandingComments, setBrandingComments] = useState(""), [charm, setCharm] = useState("None"), [size, setSize] = useState("Adjustable size 57cm (one size fits most)"), [comments, setComments] = useState("");
  const [bandPositions, setBandPositions] = useState({ base: { x: 0, y: 0 }, layerOne: { x: 0, y: 0 }, layerTwo: { x: 0, y: 0 } }), [charmPosition, setCharmPosition] = useState({ x: 0, y: 0 });
  const bandsAll = ["None", "Navy Blue", "Black", "Ivory", "Brown Leather", "Burgundy", "Rolled Terracotta", "Gold Chain", "Vintage Ribbon", "Braided Jute", "Pink Braid", "Blue Braid", "Silk Scarf", "Thin Leather"];
  const feathersAll = ["None", "Pheasant", "Small Brown Feather", "Peacock", "White", "Cream"];
  const symbolsAll = ["None", "Horseshoe", "Cactus", "Longhorn 1", "Longhorn 2", "Cross 1", "Cross 2", "Heart Outline", "Heart", "Curve", "Sun", "Arrow", "Golf Pin", "Guns Crossed", "Cowboy", "Cowboy Boot", "Snake", "Buffalo", "Bear", "Horn 1", "Horn 2", "Duck", "Wave", "Butterfly", "Flower", "Star", "Lightning Bolt", "Mountains"];
  const render = "https://cdnv2.mycustomizer.com/db091e-64/7gj5j5.png", bandClass = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-"), price = 85 + (blend === "Brim Taping" ? 45 : 0) + (feather !== "None" ? 5 : 0) + (additional === "Yes" ? 15 : 0) + (charm !== "None" ? 8 : 0);
  const reset = () => { setStep(0); setBlend("Poly"); setColor("Camel"); setBase("None"); setLayerOne("None"); setLayerTwo("None"); setTie("Tie On The Back"); setFeather("None"); setInitials(""); setAdditional("No"); setAdditionalText(""); setSymbol("None"); setBrandingComments(""); setCharm("None"); setSize("Adjustable size 57cm (one size fits most)"); setComments(""); setBandPositions({ base: { x: 0, y: 0 }, layerOne: { x: 0, y: 0 }, layerTwo: { x: 0, y: 0 } }); setCharmPosition({ x: 0, y: 0 }); };
  const setBand = (key: "base" | "layerOne" | "layerTwo") => (x: number, y: number) => setBandPositions(p => ({ ...p, [key]: { x, y } }));
  const choices = () => { if (step === 0) return <OptionGrid items={["Poly Blend", "Poly", "Brim Taping"]} value={blend} onChange={setBlend}/>; if (step === 1) return <OptionGrid items={["Brown", "Camel", "Light Pink"]} value={color} onChange={setColor}/>; if (step === 2) return <BuilderSelect value={base} onChange={setBase} items={bandsAll}/>; if (step === 3) return <BuilderSelect value={layerOne} onChange={setLayerOne} items={bandsAll}/>; if (step === 4) return <BuilderSelect value={layerTwo} onChange={setLayerTwo} items={bandsAll}/>; if (step === 5) return <OptionGrid items={["Tie On The Side", "Tie On The Back"]} value={tie} onChange={setTie}/>; if (step === 6) return <OptionGrid items={feathersAll} value={feather} onChange={setFeather} priced/>; if (step === 7) return <><p>Letters are 1/2&quot; tall. Initials are free.</p><input className="builder-input" maxLength={5} value={initials} onChange={e => setInitials(e.target.value.toUpperCase())} placeholder="Up to 5 letters"/><span className="counter">{initials.length}/5</span></>; if (step === 8) return <><OptionGrid items={["No", "Yes"]} value={additional} onChange={setAdditional}/>{additional === "Yes" && <input className="builder-input" maxLength={18} value={additionalText} onChange={e => setAdditionalText(e.target.value.toUpperCase())} placeholder="Up to 18 characters"/>}</>; if (step === 9) return <OptionGrid items={symbolsAll} value={symbol} onChange={setSymbol} priced/>; if (step === 10) return <textarea className="builder-input builder-textarea" value={brandingComments} onChange={e => setBrandingComments(e.target.value)} placeholder="Comments about branding"/>; if (step === 11) return <OptionGrid items={["None", "Gold horseshoe", "Silver cactus", "Cowboy boot", "Gold heart", "Star"]} value={charm} onChange={setCharm} priced/>; if (step === 12) return <OptionGrid items={["Adjustable size 57cm (one size fits most)", "S", "M", "L"]} value={size} onChange={setSize}/>; return <textarea className="builder-input builder-textarea" value={comments} onChange={e => setComments(e.target.value)} placeholder="Comments"/>; };
  return <div className="reference-customizer" role="dialog" aria-modal="true" aria-label="Cava custom hat builder"><div className="reference-preview"><div className="reference-preview-tools"><button aria-label="Zoom preview">⊕</button><button aria-label="Share design">↥</button><button aria-label="Start over" onClick={reset}>↻</button></div><div className="reference-hat-frame"><img src={render} alt="Temporary Rancher rendering placeholder"/>{base !== "None" && <DraggableBand name="Base" className={`reference-base-band band-${bandClass(base)}`} position={bandPositions.base} onMove={setBand("base")}/>} {layerOne !== "None" && <DraggableBand name="Layered 1" className={`reference-layer-one band-${bandClass(layerOne)}`} position={bandPositions.layerOne} onMove={setBand("layerOne")}/>} {layerTwo !== "None" && <DraggableBand name="Layered 2" className={`reference-layer-two band-${bandClass(layerTwo)}`} position={bandPositions.layerTwo} onMove={setBand("layerTwo")}/>} {feather !== "None" && <div className={`reference-overlay-feather feather-${bandClass(feather)}`} aria-label={`Feather: ${feather}`}>⌁</div>} {charm !== "None" && <DraggableCharm name={charm} glyph={charmGlyphs[charm] || "✦"} position={charmPosition} onMove={(x, y) => setCharmPosition({ x, y })}/>}<div className="reference-initials">{initials}</div><div className="reference-selection-label">{blend} · {color} · {base} · {layerOne} · {layerTwo}</div></div><button className="reference-add" onClick={onSaved}>Add to cart · ${price}.00</button></div><div className="reference-options"><button className="reference-close" aria-label="Close customizer" onClick={onClose}>×</button><div className="reference-product-title"><strong>${price}.00</strong><b>RANCHER / CAVA</b></div><div className="reference-step-count">⌃ {step + 1}/{steps.length}</div><section className="ref-section ref-step"><div className="ref-section-title"><b>{steps[step]}</b></div>{step === 0 && <p>Poly Blend and Poly are included. Brim Taping is +$45.</p>}{step === 6 && <p>Please choose a feather. These will be placed behind the band cluster.</p>}{step === 9 && <p>Symbols are burned onto the hat in white for easy viewing.</p>}{choices()}</section><div className="reference-nav"><button aria-label="Previous step" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>←</button><button aria-label="Next step" onClick={() => setStep(Math.min(steps.length - 1, step + 1))}>→</button></div><button className="reference-bottom-add" onClick={onSaved}>Add to cart · ${price}.00</button></div></div>;
}

export default function Home() {
  const [menu, setMenu] = useState(false), [hat, setHat] = useState(hats[0][0]), [size, setSize] = useState("M"), [extras, setExtras] = useState([accessories[0]]), [brand, setBrand] = useState(false), [email, setEmail] = useState(""), [notice, setNotice] = useState(""), [customOpen, setCustomOpen] = useState(false);
  const [shape, setShape] = useState("Fitted"), [color, setColor] = useState("Bone"), [baseBand, setBaseBand] = useState("None"), [layerOne, setLayerOne] = useState("None"), [layerTwo, setLayerTwo] = useState("None"), [tie, setTie] = useState("Back"), [feather, setFeather] = useState("None"), [brandText, setBrandText] = useState(""), [symbol, setSymbol] = useState("None"), [charm, setCharm] = useState("None"), [extra, setExtra] = useState("None"), [comments, setComments] = useState("");
  const total = useMemo(() => 138 + extras.length * 8 + (brand ? 12 : 0) + (feather !== "None" ? 8 : 0) + (charm !== "None" ? 8 : 0) + (extra !== "None" ? 8 : 0) + (symbol !== "None" ? 12 : 0), [extras, brand, feather, charm, extra, symbol]);
  const toggle = (x: string) => setExtras((v) => v.includes(x) ? v.filter((i) => i !== x) : [...v, x]);
  return <main onClick={e => { const target = e.target as HTMLElement; if (menu && !target.closest(".menu-button")) setMenu(false); if (!target.closest(".nav-dropdown")) document.querySelectorAll(".nav-dropdown[open]").forEach(el => { (el as HTMLDetailsElement).open = false; }); }}>{customOpen && <SimpleCustomizer onClose={() => setCustomOpen(false)} onSaved={() => { setCustomOpen(false); setNotice("Your custom hat design is saved — we’ll be in touch shortly."); }} />}
    <div className="brand-switcher"><a className="active" href="#top">CAVA HAT BAR</a><span>|</span><a href="#story">CAVA STUDIO</a></div>
    <header className="site-header"><button className="menu-button" onClick={() => setMenu(!menu)}>☰ <small>Menu</small></button><nav className={menu ? "nav-links open" : "nav-links"}><a href="#shop">JUST IN</a><NavDropdown label="COLLECTIONS" items={[["Best Sellers", "#shop"], ["Custom Edit Collection", "#shop"], ["Spring + Summer", "#shop"], ["Straw Hats", "#shop"], ["Western Collection", "#shop"], ["Packable Collection", "#shop"], ["Felt Hats", "#shop"], ["Nashville Collection", "#shop"], ["Bag Collection", "#shop"], ["Fall + Winter", "#shop"], ["Limited Edition", "#shop"], ["Men's Hats | Two Roads", "#shop"], ["Lookbook", "#story"], ["Travel", "#shop"], ["Beach", "#shop"], ["Festival + Concert", "#shop"], ["Night Out", "#shop"], ["Wedding", "#shop"]]}/><NavDropdown label="STYLES" items={[["Western", "#shop"], ["Everyday", "#shop"], ["Straw", "#shop"], ["Felt", "#shop"]]}/><NavDropdown label="ACCESSORIES" items={[["Hat Bands + Trims", "#custom"], ["Hat Pins + Charms", "#custom"], ["Hat Care", "#faq"], ["Bags", "#shop"], ["Sunglasses", "#shop"], ["Beanies + Scarves", "#shop"], ["Apparel", "#shop"], ["E-Gift Card", "#faq"]]}/><NavDropdown label="CUSTOM HAT BAR" items={[["Virtual Hat Bar", "#custom"], ["Nashville", "#custom"], ["Salt Lake City", "#custom"], ["Traveling Hat Bar", "#custom"], ["Speakeasy", "#custom"]]}/><NavDropdown label="SALE" items={[["Shop sale", "#shop"], ["End of season", "#shop"]]}/></nav><a className="wordmark" href="#top">CAVA<span>HAT BAR</span></a><div className="header-actions"><a href="#custom">⌕</a><a href="#custom">♙</a><a href="#custom">♧</a><a href="#custom">♡</a></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">THE CAVA SUMMER EDIT</p><h1>Make it<br/><em>yours.</em></h1><p className="lede">A hat for every moment — and a custom edit for the ones you’ll remember.</p><a className="button hero-button" href="#custom">SHOP YOUR STYLE <A /></a></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?auto=format&fit=crop&w=1800&q=90" alt="Woman in a wide brim hat"/><div className="image-tag">CAVA / 001<br/><span>Made for the moments</span></div></div></section>
    <section className="intro-band"><p className="eyebrow">WELCOME TO THE HAT BAR</p><h2>Come for the hat.<br/><em>Stay for the feeling.</em></h2><p>Choose your base, layer on the details, and make it unmistakably yours. Every Cava hat is an invitation to get out there and make a memory.</p><a className="text-link" href="#story">Our story <A /></a></section>
    <section className="shop-section" id="shop"><div className="section-head"><div><p className="eyebrow">SHOP THE EDIT</p><h2>Made to be worn<br/><em>on repeat.</em></h2></div><a className="text-link" href="#custom">Shop all hats <A /></a></div><div className="product-grid">{hats.map((h) => <article className="product-card" key={h[0]}><div className="product-image"><img src={h[2]} alt={h[0]}/><button>♡</button></div><div className="product-meta"><div><h3>{h[0]}</h3><p>Hand-finished felt hat</p></div><strong>{h[1]}</strong></div></article>)}</div></section>
    <section className="custom-section" id="custom"><div className="custom-intro"><p className="eyebrow">THE VIRTUAL HAT BAR</p><h2>Your hat,<br/><em>your way.</em></h2><p>Design from the comfort of home. Select your base, layer in your favorite accessories, and add your own signature. We’ll bring your edit to life.</p><div className="steps"><span><b>01</b> Pick a base</span><span><b>02</b> Add your details</span><span><b>03</b> Make it yours</span></div><button className="button outline" onClick={() => setCustomOpen(true)}>Open the full hat builder <A /></button></div><div className="builder-card"><div className="builder-preview rancher-placeholder-preview"><img src="https://cdnv2.mycustomizer.com/db091e-64/7gj5j5.png" alt="Rancher placeholder hat render"/><div className="preview-label">YOUR CAVA HAT<br/><span>{hat} · Size {size}</span></div></div><div className="builder-controls"><button className="button dark full-builder-button" onClick={() => setCustomOpen(true)}>Customize your hat <A /></button><p className="builder-note">Use our full-screen builder to choose your shape, color, layered bands, feathers, branding, charms, size, and notes.</p></div></div></section>
    {false && customOpen && <div className="customizer-overlay" role="dialog" aria-modal="true" aria-label="Cava custom hat builder"><div className="customizer-top"><button onClick={() => setCustomOpen(false)}>← Back</button></div></div>}
    <section className="size-section"><div><p className="eyebrow">FIND YOUR FIT</p><h2>Good hats<br/><em>feel good.</em></h2><p>Measure around your head, just above your eyebrows and ears. Keep the tape snug, not tight.</p><a className="text-link" href="#faq">Sizing FAQs <A /></a></div><div className="size-chart"><div className="chart-head"><span>Size</span><span>Head circumference</span><span>US hat size</span></div>{[["S","21 ⅝ – 22 in","6 ⅞ – 7"],["M","22 ¼ – 22 ¾ in","7 ⅛ – 7 ¼"],["L","23 – 23 ½ in","7 ⅜ – 7 ½"]].map(r => <div className="chart-row" key={r[0]}>{r.map(c => <span key={c}>{c}</span>)}</div>)}</div></section>
    <section className="story-section" id="story"><div className="story-image"><img src="https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=1200&q=85" alt="Friends outdoors wearing hats"/></div><div className="story-copy"><p className="eyebrow">OUR STORY</p><h2>Made for the<br/><em>good stuff.</em></h2><p>Cava started with a simple idea: the best accessories are the ones that become part of your story. We believe getting dressed should feel like an occasion, even when it’s just a Tuesday.</p><p>So we made a hat bar that feels like a conversation with your best-dressed friend — warm, personal, and a little bit unexpected.</p><a className="button dark" href="#custom">Meet Cava <A /></a></div></section>
    <section className="faq-section" id="faq"><div className="section-head"><div><p className="eyebrow">GOOD TO KNOW</p><h2>Questions,<br/><em>answered.</em></h2></div><a className="text-link" href="mailto:hello@cavahatbar.com">Ask us anything <A /></a></div><div className="faq-list">{[["How does the virtual hat bar work?","Choose your hat and details above, then book a virtual session with our hat tenders. We’ll walk you through the whole experience."],["What are the accessories made of?","Every detail is selected for personality and durability. We use vintage-inspired ribbons, natural feathers, brass, silk, and found treasures."],["Can I book Cava for my event?","Absolutely. We love a celebration. Send us a note and we’ll help bring a custom hat bar to your next gathering."],["What is your return policy?","Because custom hats are made just for you, final edits are final sale. Premade hats can be exchanged within 14 days of delivery."]].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="newsletter"><p className="eyebrow">THE CAVA LETTER</p><h2>A little more <em>good stuff.</em></h2><p>New drops, styling notes, and the occasional excuse to put on a hat.</p><form onSubmit={e => {e.preventDefault();setNotice(email ? "You’re on the list — see you soon." : "Add your email to join the list.")}}><input type="email" placeholder="Your email address" value={email} onChange={e => setEmail(e.target.value)}/><button>Join the list <A/></button></form>{notice && <small className="notice">{notice}</small>}</section>
    <footer><div className="footer-brand"><a className="wordmark" href="#top">CAVA<span>HAT BAR</span></a><p>Wear your story.</p></div><div><b>Explore</b><a href="#shop">Shop</a><a href="#custom">Custom Hat Bar</a><a href="#story">Our Story</a></div><div><b>Help</b><a href="#faq">FAQs</a><a href="#faq">Shipping + returns</a><a href="mailto:hello@cavahatbar.com">Contact</a></div><div><b>Follow along</b><a href="#top">Instagram ↗</a><a href="#top">Pinterest ↗</a><a href="#top">TikTok ↗</a></div><div className="footer-bottom"><span>© 2026 Cava Hat Bar</span><span>Made with intention in the desert</span></div></footer>
  </main>;
}
