"use client";
import { useMemo, useState } from "react";

const hats = [
  ["The Sunday Stroll", "$138", "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85"],
  ["The Desert Rose", "$148", "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?auto=format&fit=crop&w=900&q=85"],
  ["The After Hours", "$158", "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85"],
] as const;
const accessories = ["Vintage ribbon", "Feather plume", "Turquoise charm", "Brass concho", "Silk scarf"];
const A = () => <span aria-hidden="true">↗</span>;

export default function Home() {
  const [menu, setMenu] = useState(false), [hat, setHat] = useState(hats[0][0]), [size, setSize] = useState("M"), [extras, setExtras] = useState([accessories[0]]), [brand, setBrand] = useState(false), [email, setEmail] = useState(""), [notice, setNotice] = useState("");
  const total = useMemo(() => 138 + extras.length * 8 + (brand ? 12 : 0), [extras, brand]);
  const toggle = (x: string) => setExtras((v) => v.includes(x) ? v.filter((i) => i !== x) : [...v, x]);
  return <main>
    <div className="announcement">Complimentary shipping on orders $150+ <span>·</span> Virtual hat bar appointments now open <A /></div>
    <header className="site-header"><button className="menu-button" onClick={() => setMenu(!menu)}>☰ <small>Menu</small></button><nav className={menu ? "nav-links open" : "nav-links"}><a href="#shop">Shop</a><a href="#custom">Custom Hat Bar</a><a href="#story">Our Story</a><a href="#faq">FAQs</a></nav><a className="wordmark" href="#top">CAVA<span>HAT BAR</span></a><div className="header-actions"><a href="#custom">⌕</a><a href="#custom">♙</a><a href="#custom">Bag (0)</a></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">THE CAVA EXPERIENCE</p><h1>Make a hat.<br/><em>Make it yours.</em></h1><p className="lede">A little western, a little wonderful. Build a one-of-a-kind hat from wherever you are, and wear the story everywhere.</p><a className="button dark" href="#custom">Build your hat <A /></a></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?auto=format&fit=crop&w=1600&q=85" alt="Woman in a wide brim hat"/><div className="image-tag">CAVA / 001<br/><span>Made for the moments</span></div></div></section>
    <section className="intro-band"><p className="eyebrow">WELCOME TO THE HAT BAR</p><h2>Come for the hat.<br/><em>Stay for the feeling.</em></h2><p>Choose your base, layer on the details, and make it unmistakably yours. Every Cava hat is an invitation to get out there and make a memory.</p><a className="text-link" href="#story">Our story <A /></a></section>
    <section className="shop-section" id="shop"><div className="section-head"><div><p className="eyebrow">SHOP THE EDIT</p><h2>Made to be worn<br/><em>on repeat.</em></h2></div><a className="text-link" href="#custom">Shop all hats <A /></a></div><div className="product-grid">{hats.map((h) => <article className="product-card" key={h[0]}><div className="product-image"><img src={h[2]} alt={h[0]}/><button>♡</button></div><div className="product-meta"><div><h3>{h[0]}</h3><p>Hand-finished felt hat</p></div><strong>{h[1]}</strong></div></article>)}</div></section>
    <section className="custom-section" id="custom"><div className="custom-intro"><p className="eyebrow">THE VIRTUAL HAT BAR</p><h2>Your hat,<br/><em>your way.</em></h2><p>Design from the comfort of home. Select your base, layer in your favorite accessories, and add your own signature. We’ll bring your edit to life.</p><div className="steps"><span><b>01</b> Pick a base</span><span><b>02</b> Add your details</span><span><b>03</b> Make it yours</span></div><a className="button outline" href="mailto:hello@cavahatbar.com?subject=Virtual Hat Bar Appointment">Book a virtual experience <A /></a></div><div className="builder-card"><div className="builder-preview"><div className="hat-shape"><div className="hat-crown"/><div className="hat-brim"/><div className="hat-ribbon"/></div><div className="preview-label">YOUR CAVA HAT<br/><span>{hat} · Size {size}</span></div></div><div className="builder-controls"><div className="control-row"><div><label>01 / Base hat</label><select value={hat} onChange={e => setHat(e.target.value)}>{hats.map(h => <option key={h[0]}>{h[0]}</option>)}</select></div><div><label>Size</label><div className="size-buttons">{["S","M","L"].map(s => <button className={size === s ? "selected" : ""} onClick={() => setSize(s)} key={s}>{s}</button>)}</div></div></div><div className="control-block"><label>02 / Layer your accessories <small>$8 each</small></label><div className="choice-grid">{accessories.map(x => <button className={extras.includes(x) ? "choice selected" : "choice"} onClick={() => toggle(x)} key={x}><span>{extras.includes(x) ? "✓" : "+"}</span>{x}</button>)}</div></div><div className="control-block"><label>03 / Add your signature <small>$12</small></label><button className={brand ? "branding selected" : "branding"} onClick={() => setBrand(!brand)}><span>✦</span><div><b>Custom branding</b><small>Add initials, a word, or a little something extra.</small></div><strong>{brand ? "✓" : "+"}</strong></button></div><div className="builder-total"><div><small>YOUR ESTIMATED TOTAL</small><strong>${total}.00</strong></div><button className="button dark" onClick={() => setNotice("Your custom edit is saved — we’ll be in touch shortly.")}>Save my design <A /></button></div>{notice && <p className="notice">{notice}</p>}</div></div></section>
    <section className="size-section"><div><p className="eyebrow">FIND YOUR FIT</p><h2>Good hats<br/><em>feel good.</em></h2><p>Measure around your head, just above your eyebrows and ears. Keep the tape snug, not tight.</p><a className="text-link" href="#faq">Sizing FAQs <A /></a></div><div className="size-chart"><div className="chart-head"><span>Size</span><span>Head circumference</span><span>US hat size</span></div>{[["S","21 ⅝ – 22 in","6 ⅞ – 7"],["M","22 ¼ – 22 ¾ in","7 ⅛ – 7 ¼"],["L","23 – 23 ½ in","7 ⅜ – 7 ½"]].map(r => <div className="chart-row" key={r[0]}>{r.map(c => <span key={c}>{c}</span>)}</div>)}</div></section>
    <section className="story-section" id="story"><div className="story-image"><img src="https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=1200&q=85" alt="Friends outdoors wearing hats"/></div><div className="story-copy"><p className="eyebrow">OUR STORY</p><h2>Made for the<br/><em>good stuff.</em></h2><p>Cava started with a simple idea: the best accessories are the ones that become part of your story. We believe getting dressed should feel like an occasion, even when it’s just a Tuesday.</p><p>So we made a hat bar that feels like a conversation with your best-dressed friend — warm, personal, and a little bit unexpected.</p><a className="button dark" href="#custom">Meet Cava <A /></a></div></section>
    <section className="faq-section" id="faq"><div className="section-head"><div><p className="eyebrow">GOOD TO KNOW</p><h2>Questions,<br/><em>answered.</em></h2></div><a className="text-link" href="mailto:hello@cavahatbar.com">Ask us anything <A /></a></div><div className="faq-list">{[["How does the virtual hat bar work?","Choose your hat and details above, then book a virtual session with our hat tenders. We’ll walk you through the whole experience."],["What are the accessories made of?","Every detail is selected for personality and durability. We use vintage-inspired ribbons, natural feathers, brass, silk, and found treasures."],["Can I book Cava for my event?","Absolutely. We love a celebration. Send us a note and we’ll help bring a custom hat bar to your next gathering."],["What is your return policy?","Because custom hats are made just for you, final edits are final sale. Premade hats can be exchanged within 14 days of delivery."]].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="newsletter"><p className="eyebrow">THE CAVA LETTER</p><h2>A little more <em>good stuff.</em></h2><p>New drops, styling notes, and the occasional excuse to put on a hat.</p><form onSubmit={e => {e.preventDefault();setNotice(email ? "You’re on the list — see you soon." : "Add your email to join the list.")}}><input type="email" placeholder="Your email address" value={email} onChange={e => setEmail(e.target.value)}/><button>Join the list <A/></button></form>{notice && <small className="notice">{notice}</small>}</section>
    <footer><div className="footer-brand"><a className="wordmark" href="#top">CAVA<span>HAT BAR</span></a><p>Wear your story.</p></div><div><b>Explore</b><a href="#shop">Shop</a><a href="#custom">Custom Hat Bar</a><a href="#story">Our Story</a></div><div><b>Help</b><a href="#faq">FAQs</a><a href="#faq">Shipping + returns</a><a href="mailto:hello@cavahatbar.com">Contact</a></div><div><b>Follow along</b><a href="#top">Instagram ↗</a><a href="#top">Pinterest ↗</a><a href="#top">TikTok ↗</a></div><div className="footer-bottom"><span>© 2026 Cava Hat Bar</span><span>Made with intention in the desert</span></div></footer>
  </main>;
}
