"use client";
import {useEffect,useState} from 'react';
import HatEditor,{type HatDesign} from './hat-editor';
import {catalog} from './catalog';
import {cowboyHatRenders} from './hat-assets';
import './cava-store.css';
type Product=typeof catalog[number];
type BagItem={id:string;name:string;size:string;price:number;image:string;design?:HatDesign};
const menus:Record<string,Array<[string,string]>>={SHOP:[['All hats','#shop'],['Premade hats','#shop'],['Build your own','#custom']],STYLES:[['Western hats','#shop'],['Custom cowboy hats','#custom']],ACCESSORIES:[['Base bands','#custom'],['Layered bands','#custom'],['Feathers & charms','#custom'],['Branding','#custom']],'CUSTOM HAT BAR':[['Design your hat','#custom'],['How it works','#how-it-works'],['Find your size','#size-chart']],ABOUT:[['Our story','#story'],['FAQs','#faq']]};
export default function Storefront(){
 const [menu,setMenu]=useState<string|null>(null),[mobile,setMobile]=useState(false),[builder,setBuilder]=useState(false),[edit,setEdit]=useState<HatDesign|undefined>(),[editId,setEditId]=useState<string|null>(null),[filter,setFilter]=useState('All'),[sort,setSort]=useState('Featured'),[filtersOpen,setFiltersOpen]=useState(false),[product,setProduct]=useState<Product|null>(null),[photo,setPhoto]=useState(false),[size,setSize]=useState('M'),[bag,setBag]=useState<BagItem[]>([]),[bagOpen,setBagOpen]=useState(false),[ready,setReady]=useState(false),[checkout,setCheckout]=useState(false);
 useEffect(()=>{try{const stored=localStorage.getItem('cava-development-bag');if(stored){const data=JSON.parse(stored);if(Array.isArray(data))setBag(data)}}catch{}setReady(true);const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(null);setMobile(false);setProduct(null);setBagOpen(false)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('cava-development-bag',JSON.stringify(bag))},[bag,ready]);
 const openBuilder=()=>{setEdit(undefined);setEditId(null);setBuilder(true);setMenu(null);setMobile(false)};
 const saveDesign=(design:HatDesign)=>{const id=editId??crypto.randomUUID();setBag(items=>[...items.filter(i=>i.id!==id),{id,name:`Custom ${design.shape} hat`,size:design.size,price:design.total,image:cowboyHatRenders[design.shape][design.color],design}]);setBuilder(false);setBagOpen(true);setCheckout(false)};
 const visible=catalog.filter(p=>filter==='All'||p.color===filter).sort((a,b)=>sort==='Price: low to high'?a.price-b.price:sort==='Price: high to low'?b.price-a.price:0);
 return <main className="cava-store" onClick={e=>{if(!(e.target as HTMLElement).closest('.cava-navigation')){setMenu(null);setMobile(false)}}}>
 <div className="cava-topbar"><span>CAVA HAT BAR</span><span>DEVELOPMENT PREVIEW · ORDERS ARE NOT LIVE</span></div>
 <header className="cava-header"><a className="cava-logo" href="#shop">CAVA <span>HAT BAR</span></a><div className="cava-navigation"><button className="cava-menu-toggle" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>☰ Menu</button><nav className={mobile?'expanded':''}>{Object.keys(menus).map(name=><div key={name} className="cava-menu"><button aria-expanded={menu===name} onClick={()=>setMenu(menu===name?null:name)}>{name} <span>⌄</span></button>{menu===name&&<div className="cava-dropdown">{menus[name].map(([label,url])=><a key={label} href={url} onClick={()=>{setMenu(null);setMobile(false);if(url==='#custom')openBuilder()}}>{label}</a>)}</div>}</div>)}</nav></div><button className="cava-bag-button" onClick={()=>{setBagOpen(true);setCheckout(false)}} aria-label={`Open bag, ${bag.length} items`}>Bag <span>{bag.length}</span></button></header>
 <section className="cava-collection" id="shop"><h1>THE WESTERN HAT COLLECTION</h1><div className="cava-collection-toolbar"><button onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}>☷ &nbsp; Filters</button><span>{visible.length} styles</span><label>Sort by: <select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price: low to high</option><option>Price: high to low</option></select></label></div><div className="cava-catalog-layout"><aside className={filtersOpen?'cava-filters visible':'cava-filters'}><details open><summary>Collection</summary><button className="active" onClick={()=>setFilter('All')}>Premade western hats</button><button onClick={openBuilder}>Custom hat bar →</button></details><details open><summary>Color</summary>{['All','Cream','Brown','Black','Chocolate','Beige'].map(c=><label key={c}><input type="radio" name="color-filter" checked={filter===c} onChange={()=>setFilter(c)}/>{c}</label>)}</details><details><summary>Size</summary><p>All preview styles include S, M, and L.</p><a href="#size-chart">View size chart →</a></details><p className="catalog-note">Preview collection. Photos and prices will be replaced with Cava’s final products.</p></aside><div className="cava-products">{visible.map(p=><article key={p.id}><button className="cava-product-photo" onClick={()=>{setProduct(p);setPhoto(false);setSize('M')}} aria-label={`View ${p.name}`}><img src={p.image} alt={`${p.name} hat`}/><img className="worn-photo" src={p.worn} alt={`${p.name} worn by a model`} loading="lazy"/></button><button className="cava-product-name" onClick={()=>{setProduct(p);setPhoto(false)}}>{p.name}</button><p>${p.price}.00</p><div className="cava-product-swatch"><span style={{background:({Cream:'#e4d9c6',Brown:'#977349',Black:'#242220',Chocolate:'#493026',Beige:'#c8b293'} as Record<string,string>)[p.color]}}/>{p.color}</div></article>)}</div></div></section>
 <section className="cava-custom-banner" id="custom"><img src="/cowboy-renderings/1dbm00.png" alt="Mocha cowboy hat ready to customize"/><div><p className="cava-eyebrow">THE VIRTUAL HAT BAR</p><h2>Make it your own.</h2><p>Start with a hat you love. Layer your bands, place a feather, and add the finishing details.</p><p>Accessories $8 each. Branding $12 per placement.</p><button onClick={openBuilder}>BUILD YOUR HAT →</button></div></section>
 <section className="cava-how" id="how-it-works"><h2>Your hat, from first choice to final edit.</h2><div>{[['01','Choose your hat','Find your shape, color, and size.'],['02','Make it personal','Add bands, feathers, charms, and branding. Select each piece to move, rotate, or resize it.'],['03','Review every detail','Save your final design to your bag. You can reopen it and keep editing.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="cava-size" id="size-chart"><div><p className="cava-eyebrow">FIND YOUR FIT</p><h2>Good hats feel good.</h2><p>Measure around your head, just above your eyebrows and ears. Keep the tape snug, not tight.</p></div><table><thead><tr><th>Size</th><th>Head circumference</th><th>US hat size</th></tr></thead><tbody>{[['S','21⅝–22 in','6⅞–7'],['M','22¼–22¾ in','7⅛–7¼'],['L','23–23½ in','7⅜–7½']].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></section>
 <section className="cava-story" id="story"><p className="cava-eyebrow">OUR STORY</p><h2>A hat that feels like you.</h2><p>Cava Hat Bar is a place to choose your own details and create something personal. From a simple band to a fully layered design, every choice is yours.</p><button onClick={openBuilder}>EXPLORE THE HAT BAR →</button></section>
 <section className="cava-faq" id="faq"><h2>Questions, answered.</h2>{[['How do I move an earlier band?','Click or tap the piece itself, or choose its named button beneath the preview. Each piece keeps its own position. The arrow controls let you move a covered piece without disturbing the others.'],['How much are the accessories?','Each base band, layered band, feather, and charm is $8. Branding is $12 per placement. Your total updates as you build.'],['Can I edit my design later?','Yes. Save it to your bag, then choose Edit design. This development version keeps your bag in this browser.'],['Can I place an order right now?','This is a development preview. Payments and confirmation emails will be connected when Cava’s Shopify store is ready.'],['Will you offer virtual event bookings?','Google Meet availability and event booking are planned for a later release.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
 <footer className="cava-footer"><div><a className="cava-logo" href="#shop">CAVA <span>HAT BAR</span></a><p>Wear your story.</p></div><div><b>EXPLORE</b><a href="#shop">Premade hats</a><button onClick={openBuilder}>Custom hat bar</button><a href="#story">Our story</a></div><div><b>GOOD TO KNOW</b><a href="#size-chart">Size chart</a><a href="#faq">FAQs</a><button onClick={()=>setBagOpen(true)}>Your saved designs</button></div><small>© 2026 Cava Hat Bar · Development preview</small></footer>
 {product&&<div className="cava-sheet-backdrop" onClick={()=>setProduct(null)}><section className="cava-product-dialog" role="dialog" aria-modal="true" aria-label={product.name} onClick={e=>e.stopPropagation()}><button className="cava-close" onClick={()=>setProduct(null)} aria-label="Close product">×</button><div><img src={photo?product.worn:product.image} alt={photo?`${product.name} worn by a model`:product.name}/><button className="cava-text-button" onClick={()=>setPhoto(!photo)}>{photo?'View hat':'See it worn'} ↔</button></div><div><p className="cava-eyebrow">PREMADE COLLECTION</p><h2>{product.name}</h2><p>${product.price}.00</p><label>Size</label><div className="cava-size-picks">{['S','M','L'].map(s=><button key={s} aria-pressed={size===s} onClick={()=>setSize(s)}>{s}</button>)}</div><a className="cava-text-button" href="#size-chart" onClick={()=>setProduct(null)}>Size chart</a><button className="cava-solid" onClick={()=>{setBag(items=>[...items,{id:crypto.randomUUID(),name:product.name,size,price:product.price,image:product.image}]);setProduct(null);setBagOpen(true)}}>ADD TO BAG →</button><p className="catalog-note">Development product. Final availability and details are pending.</p></div></section></div>}
 {bagOpen&&<div className="cava-sheet-backdrop" onClick={()=>setBagOpen(false)}><section className="cava-bag" role="dialog" aria-modal="true" aria-label="Your bag" onClick={e=>e.stopPropagation()}><button className="cava-close" onClick={()=>setBagOpen(false)} aria-label="Close bag">×</button><h2>Your bag <span>({bag.length})</span></h2>{bag.length===0?<p>Your next favorite hat starts here.</p>:bag.map(item=><article key={item.id}><img src={item.image} alt={item.name}/><div><h3>{item.name}</h3><p>Size {item.size} · ${item.price}.00</p>{item.design&&<><p>{item.design.pieces.map(p=>p.name).join(' · ')||'No accessories'}</p><button onClick={()=>{setEdit(item.design);setEditId(item.id);setBagOpen(false);setBuilder(true)}}>Edit design</button></>}<button onClick={()=>setBag(items=>items.filter(i=>i.id!==item.id))}>Remove</button></div></article>)}{bag.length>0&&<><div className="cava-bag-total"><b>Subtotal</b><b>${bag.reduce((t,i)=>t+i.price,0)}.00</b></div><button className="cava-solid" onClick={()=>setCheckout(true)}>CHECKOUT →</button></>}{checkout&&<div className="cava-dev-checkout" role="status"><h3>Your design is saved.</h3><p>Checkout is in development. Payments and automatic emails will become available when Cava’s Shopify store is connected. No order has been placed.</p></div>}<button className="cava-text-button" onClick={()=>setBagOpen(false)}>Continue exploring</button></section></div>}
 {builder&&<HatEditor initial={edit} onClose={()=>setBuilder(false)} onSave={saveDesign}/>}
 </main>;
}
